name: lm_feedback
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch
  - transformers
  - tokenizers
  - pip=23.0.1
  - pandas
  - lightning
  - matplotlib
