name: lm_feedback
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/free
  - menpo
  - roebel
dependencies:
  - python=3.9
  - pytorch
  - pytorch-cuda=11.8
  - transformers==4.14.1
  - tokenizers==0.10.3
  - pip=23.0.1
  - pandas
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.2
    - attrs==22.2.0
    - contourpy==1.0.7
    - cycler==0.11.0
    - docstring-parser==0.15
    - fonttools==4.39.3
    - frozenlist==1.3.3
    - fsspec==2023.3.0
    - hydra-core==1.3.2
    - importlib-resources==5.12.0
    - jsonargparse==4.20.0
    - kiwisolver==1.4.4
    - lightning-utilities==0.8.0
    - markdown-it-py==2.2.0
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - multidict==6.0.4
    - omegaconf==2.3.0
    - pillow==9.4.0
    - protobuf==3.20.3
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pytorch-lightning==2.0.0
    - rich==13.3.3
    - tensorboardx==2.6
    - torchmetrics==0.11.4
    - typeshed-client==2.2.0
    - yarl==1.8.2
    - zipp==3.15.0
