name: lm_feedback
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - matplotlib
  - pandas
  - pip
  - python=3.12.4
  - pytorch
  - pytorch-cuda=11.8
  - lightning
  - trl
  - conda-forge::huggingface_hub=0.24.2
  - conda-forge::transformers=4.43
