name: lm_feedback
channels:
  - defaults
  - pytorch
dependencies:
  - lightning
  - matplotlib
  - pandas
  - pip=23.0.1
  - python==3.12.4
  - pytorch
  - tokenizers
  - conda-forge::transformers=4.43
  - conda-forge::huggingface_hub=0.24.2
